### ISSUE TITLE
CRC32 calls rand() but doesn't use srand() to set the seed

### ISSUE THREAD

**Issue by gmarkall** [mageec/beebs#40]
This might result in different results (and failing the verify_benchmark() check) on different platforms.

**Comment by jeremybennett** [comment]
More generally there is no guarantee that `rand ()` on different architectures or library versions will yield a consistent sequence.  If nothing else `RAND_MAX` may have different values.  The solution is to use a fixed version of `rand ()`  which yields a fixed set of values, all within the range [0, 32767], being the smallest permitted value of `RAND_MAX`

Fix coming up shortly....
